version: '3.9'
services:

  back-end:
    container_name: back-end
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - rabbitmq
    networks:
      host:
    environment:
      JASYPT_ENCRYPTION_KEY: fX=Gq9MS#Ue%YXf@76HY-wVPz

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      host:

networks:
  host:
