version: '3.9'
services:

  back-end:
    environment:
      SPRING_PROFILES_ACTIVE: dev
    container_name: back-end
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - rabbitmq
    networks:
      host:

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      host:

networks:
  host:
