
spring:
  datasource:
    url: jdbc:h2:mem:spring-boot-course?useSSL=false&ServerTimezone=UTC
    driver-class-name: org.h2.Driver
    username: user
    password: user
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: update
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    time-zone: America/Sao_Paulo
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    queue:
      registered-purchase: REGISTERED_PURCHASE
      pending-purchase: PENDING_PURCHASE_APPROVE
      approved-purchase: APPROVED_PURCHASE
      reproved-purchase: REPROVED_PURCHASE
      update-purchase-status: UPDATE_PURCHASE_STATUS
    listener:
      simple:
        retry:
          max-attempts: 5
      direct:
        auto-startup: true
    template:
      retry:
        max-attempts: 5

server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always
  servlet:
    context-path: /purchase-api

external-apis:
  zipcodeapi:
    url: https://www.zipcodeapi.com/rest/
    application-key: DemoOnly00ycwXVYwYOViHQihkVl2o2v5WjBtwdae9xLiRfTPEeGhTSpFqahzS7B

jasypt:
  encryptor:
    password: 0123456789