name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  ZIPCODE_APPLICATION_KEY: pKQ16ODvAw3XN9O13vSHF8nsB5mEvMeaRWIw5pn7ehBO4ZBuzbAI1TP2wmtH7Fn3

jobs:
  tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  build:
    needs: tests
    name: Build maven package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Cache local Maven repository
    - uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Build package jar
      run: mvn -B package -DskipeTests --file pom.xml
    - name: Upload .jar
      uses: actions/upload-artifact@v2
      with: 
        name: artifact
        path: target/app.jar
